version: "3.7"
services:

  typo3:
    image: edepta/typo3-docker:10.4
    volumes:
      - typo3:/var/www/html/
    ports:
      - 80:80
    environment:
      TYPO3_ADMIN_USERNAME: admin
      TYPO3_ADMIN_PASSWORD: ShouldBeAStrongPassword
      TYPO3_DB_HOST: mysql
      TYPO3_DB_NAME: typo3
      TYPO3_DB_USERNAME: typo3
      TYPO3_DB_PASSWORD: ShouldBeAStrongPassword

  mysql:
    image: mariadb:latest
    volumes:
      - mysql:/var/lib/mysql/
    environment:
      MYSQL_DATABASE: typo3
      MYSQL_USER: typo3
      MYSQL_PASSWORD: ShouldBeAStrongPassword
      MYSQL_ROOT_PASSWORD: ShouldBeAStrongPassword
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  typo3:
  mysql:
